POST https://node-do-zero-siwh.onrender.com/videos
Content-type: application/json

{
    "title": "Video node node",
    "description": "Video Description 01",
    "duration": 180
}

###

GET https://node-do-zero-siwh.onrender.com/videos
# GET https://node-do-zero-siwh.onrender.com/videos?search=as

###

PUT https://node-do-zero-siwh.onrender.com/videos/e2b9ad93-0124-4d25-ae5a-94fc442ee710
Content-type: application/json

{
    "title": "Video 03",
    "description": "Video Description 03",
    "duration": 182
}

###

DELETE https://node-do-zero-siwh.onrender.com/videos/e2b9ad93-0124-4d25-ae5a-94fc442ee710
